export const ADVENTURE_LEVELS = [
  {
    id: 1,
    table: 1,
    nameKey: 'level_1_name',
    descKey: 'level_1_desc',
    image: 'forest.png',
    requiredStars: 0,
  },
  {
    id: 2,
    table: 2,
    nameKey: 'level_2_name',
    descKey: 'level_2_desc',
    image: 'river.png',
    requiredStars: 2,
  },
  {
    id: 3,
    table: 5,
    nameKey: 'level_3_name',
    descKey: 'level_3_desc',
    image: 'forest.png',
    requiredStars: 4,
  },
  {
    id: 4,
    table: 10,
    nameKey: 'level_4_name',
    descKey: 'level_4_desc',
    image: 'river.png',
    requiredStars: 6,
  },
  {
    id: 5,
    table: 3,
    nameKey: 'level_5_name',
    descKey: 'level_5_desc',
    image: 'forest.png',
    requiredStars: 8,
  },
  {
    id: 6,
    table: 4,
    nameKey: 'level_6_name',
    descKey: 'level_6_desc',
    image: 'river.png',
    requiredStars: 10,
  },
  {
    id: 7,
    table: 6,
    nameKey: 'level_7_name',
    descKey: 'level_7_desc',
    image: 'forest.png',
    requiredStars: 12,
  },
  {
    id: 8,
    table: 7,
    nameKey: 'level_8_name',
    descKey: 'level_8_desc',
    image: 'river.png',
    requiredStars: 14,
  },
  {
    id: 9,
    table: 8,
    nameKey: 'level_9_name',
    descKey: 'level_9_desc',
    image: 'forest.png',
    requiredStars: 16,
  },
  {
    id: 10,
    table: 9,
    nameKey: 'level_10_name',
    descKey: 'level_10_desc',
    image: 'river.png',
    requiredStars: 18,
  },
];
